---
# tasks file for soulseek
# create folders for soulseek
- name: create folders for soulseek
  file:
    path: /home/{{ansible_user}}/soulseek/
    state: directory
    owner: {{ansible_user}}
    group: {{ansible_user}}
    mode: '0700'
    require:
      - user: {{ansible_user}}

# create soulseek docker container
- name: create soulseek docker container
  docker_container:
    name: soulseek
    image: realies/soulseek
    volumes:
      - "{{docker_home}}/soulseek/appdata:/data/.SoulseekQt"
      - "{{docker_home}}/soulseek/downloads:/data/Soulseek Downloads"
      - "{{docker_home}}/soulseek/logs:/data/Soulseek Chat Logs"
      - "{{docker_home}}/soulseek/shared:/data/Soulseek Shared Folder"
    ports: 
      - "{{soulseek_port}}:6080" 
    state: started
    memory: "{{ soulseek_memory }}"
  when: soulseek_enabled is true

- name: Stop soulseek
  docker_container:
    name: "{{ soulseek_container_name }}"
    state: absent
  when: soulseek_enabled is false
