---
- name: dozzle Docker Container
  docker_container:
    name: dozzle
    image: amir20/dozzle:latest
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "{{ dozzle_port_http }}:8080"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    memory: "{{ dozzle_memory }}"

