# - hosts: localhost
#   gather_facts: true
#   become: true
#   become_user: "{{ lookup('env', 'USER') }}"

# - name: update repositories
#   apt: update_cache=yes
#   become_user: root
#   changed_when: False
  
#   vars:
#     user: "{{ ansible_user_id }}"


# - name: check if cargo is installed
#   shell: command -v go
#   register: cargo_exists
#   ignore_errors: True
#   become_user: alex


- name: Check is ls installed
  shell: command -v cargo >/dev/null 2>&1
  register: cargo_exists
  ignore_errors: True


- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust


# - name: "Rust | Install"
#   shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
#   changed_when: false

# - name: "Rust | Install toolchain"
#   shell: "{{ fubarhouse_user_dir }}/.cargo/bin/rustup toolchain install {{ rust_version }}"
#   register: rustup_toolchain
#   changed_when: '"installed" in rustup_toolchain.stdout'
#   when: rust_version is defined