---
- hosts: all
  roles:
    ###
    ### Requirements
    ###
    - role: ansible-nas-users
      tags:
        - ansible-nas-users
        - ansible-nas
      when: (ansible_nas_users_enabled | default(False))

    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint
      when: (bertvv_samba_enabled | default(False))

    - role: geerlingguy.nfs
      tags:
        - nfs
        - skip_ansible_lint
      when: (nfs_enabled | default(False))

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

      when: (geerlingguy_docker_enabled | default(False))

    - role: hurricanehrndz.rustup
      tags:
        - rustup
      when: (rustup_enabled | default(False))

    - role: rust
      tags:
        - rust
      when:
        - rust_enabled | default(False)
    - role: artis3n.tailscale
      tags:
        - tailscale
      when: (tailscale_enabled | default(False))

    - role: geerlingguy.ansible
      tags:
        - ansible
      when: (ansible_enabled | default(False))

    - role: docker
      tags:
        - docker
      when: (docker_enabled | default(False))

    - role: geerlingguy.git
      tags:
        - git
      when: (git_enabled | default(False))

    - role: geerlingguy.go
      tags:
        - go
      when: (go_enabled | default(False))

    - role: geerlingguy.ntp
      tags:
        - ntp
      when: (ntp_role_enabled | default(False))

    - role: linux
      tags:
        - linux
      when:
        - linux_enabled | default(False)

    - role: taskfzf
      tags:
        - taskfzf
      when:
        - taskfzf_enabled | default(False)
    - role: taskwarrior
      tags:
        - taskwarrior
      when:
        - taskwarrior_enabled | default(False)
    - role: hosts
      tags:
        - hosts
      when:
        - hosts_enabled | default(False)

    ###
    ### Ansible-NAS Roles
    ###
    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas
      when: (ansible_nas_general_enabled | default(False))

    - role: ansible-nas-docker
      tags:
        - ansible-nas-docker
        - ansible-nas
      when: (ansible_nas_docker_enabled | default(False))

    ###
    ### Applications
    ###
    - role: airsonic
      tags:
        - airsonic
      when: (airsonic_enabled | default(False))

    - role: bazarr
      tags:
        - bazarr
      when: (bazarr_enabled | default(False))

    - role: bitwarden
      tags:
        - bitwarden
      when: (bitwarden_enabled | default(False))

    - role: booksonic
      tags:
        - booksonic
      when: (booksonic_enabled | default(False))

    - role: calibre
      tags:
        - calibre
      when: (calibre_enabled | default(False))

    - role: cloudcmd
      tags:
        - cloudcmd
      when: (cloudcmd_enabled | default(False))

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns
      when: (cloudflare_ddns_enabled | default(False))

    - role: code-server
      tags:
        - code-server
      when: (code_server_enabled | default(False))

    - role: couchpotato
      tags:
        - couchpotato
      when: (couchpotato_enabled | default(False))

    - role: dashy
      tags:
        - dashy
      when: (dashy_enabled | default(False))

    - role: deluge
      tags:
        - deluge
      when: (deluge_enabled | default(False))

    - role: dokuwiki
      tags:
        - dokuwiki
      when: (dokuwiki_enabled | default(False))

    - role: drone-ci
      tags:
        - drone_ci
      when: (drone_ci_enabled | default(False))

    - role: duplicacy
      tags:
        - duplicacy
      when: (duplicacy_enabled | default(False))

    - role: duplicati
      tags:
        - duplicati
      when: (duplicati_enabled | default(False))

    - role: emby
      tags:
        - emby
      when: (emby_enabled | default(False))

    - role: esphome
      tags:
        - esphome
      when: (esphome_enabled | default(False))

    - role: firefly
      tags:
        - firefly
      when: (firefly_enabled | default(False))

    - role: actualbudget
      tags:
        - actualbudget
      when: (actual_enabled | default(False))

    - role: homepage
      tags:
        - homepage
      when: (homepage_enabled | default(False))

    - role: freshrss
      tags:
        - freshrss
      when: (freshrss_enabled | default(False))

    - role: get_iplayer
      tags:
        - get_iplayer
      when: (get_iplayer_enabled | default(False))

    - role: gitea
      tags:
        - gitea
      when: (gitea_enabled | default(False))

    - role: gitlab
      tags:
        - gitlab
      when: (gitlab_enabled | default(False))

    - role: glances
      tags:
        - glances
      when: (glances_enabled | default(False))

    - role: gotify
      tags:
        - gotify
      when: (gotify_enabled | default(False))

    - role: guacamole
      tags:
        - guacamole
      when: (guacamole_enabled | default(False))

    - role: healthchecks.io
      tags:
        - healthchecks.io
      when: (healthchecks_enabled | default(False))

    - role: heimdall
      tags:
        - heimdall
      when: (heimdall_enabled | default(False))

    - role: hello_world
      tags:
        - hello_world
      when: (hello_world_enabled | default(False))

    - role: homeassistant
      tags:
        - homeassistant
      when: (homeassistant_enabled | default(False))

    - role: homebridge
      tags:
        - homebridge
      when: (homebridge_enabled | default(False))

    - role: jackett
      tags:
        - jackett
      when: (jackett_enabled | default(False))

    - role: jellyfin
      tags:
        - jellyfin
      when: (jellyfin_enabled | default(False))

    - role: joomla
      tags:
        - joomla
      when: (joomla_enabled | default(False))

    - role: komga
      tags:
        - komga
      when: (komga_enabled | default(False))

    - role: krusader
      tags:
        - krusader
      when: (krusader_enabled | default(False))

    - role: lidarr
      tags:
        - lidarr
      when: (lidarr_enabled | default(False))

    - role: mealie
      tags:
        - mealie
      when: (mealie_enabled | default(False))

    - role: minecraft-server
      tags:
        - minecraft-server
      when: (minecraft_server_enabled | default(False))

    - role: minidlna
      tags:
        - minidlna
      when: (minidlna_enabled | default(False))

    - role: miniflux
      tags:
        - miniflux
      when: (miniflux_enabled | default(False))

    - role: mosquitto
      tags:
        - mosquitto
      when: (mosquitto_enabled | default(False))

    - role: mylar
      tags:
        - mylar
      when: (mylar_enabled | default(False))

    - role: mymediaforalexa
      tags:
        - mymediaforalexa
      when: (mymediaforalexa_enabled | default(False))

    - role: n8n
      tags:
        - n8n
      when: (n8n_enabled | default(False))

    - role: navidrome
      tags:
        - navidrome
      when: (navidrome_enabled | default(False))

    - role: netbootxyz
      tags:
        - netbootxyz
      when: (netbootxyz_enabled | default(False))

    - role: netdata
      tags:
        - netdata
      when: (netdata_enabled | default(False))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: nomad
      tags:
        - nomad
      when: (nomad_enabled | default(False))

    - role: nzbget
      tags:
        - nzbget
      when: (nzbget_enabled | default(False))

    - role: octoprint
      tags:
        - octoprint
      when: (octoprint_enabled | default(False))

    - role: ombi
      tags:
        - ombi
      when: (ombi_enabled | default(False))

    - role: openhab
      tags:
        - openhab
      when: (openhab_enabled | default(False))

    - role: organizr
      tags:
        - organizr
      when: (organizr_enabled | default(False))

    - role: overseerr
      tags:
        - overseerr
      when: (overseerr_enabled | default(False))

    - role: paperless_ng
      tags:
        - paperless_ng
      when: (paperless_ng_enabled | default(False))

    - role: piwigo
      tags:
        - piwigo
      when: (piwigo_enabled | default(False))

    - role: plex
      tags:
        - plex
      when: (plex_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: prowlarr
      tags:
        - prowlarr
      when: (prowlarr_enabled | default(False))

    - role: pyload
      tags:
        - pyload
      when: (pyload_enabled | default(False))

    - role: pytivo
      tags:
        - pytivo
      when: (pytivo_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: route53_ddns
      tags:
        - route53_ddns
      when: (route53_ddns_enabled | default(False))

    - role: rssbridge
      tags:
        - rssbridge
      when: (rssbridge_enabled | default(False))

    - role: sabnzbd
      tags:
        - sabnzbd
      when: (sabnzbd_enabled | default(False))

    - role: sickchill
      tags:
        - sickchill
      when: (sickchill_enabled | default(False))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(False))

    - role: speedtest-tracker
      tags:
        - speedtest-tracker
      when: (speedtest_tracker_enabled | default(False))

    - role: stats
      tags:
        - stats
      when: (stats_enabled | default(False))

    - role: syncthing
      tags:
        - syncthing
      when: (syncthing_enabled | default(False))

    - role: tautulli
      tags:
        - tautulli
      when: (tautulli_enabled | default(False))

    - role: thelounge
      tags:
        - thelounge
      when: (thelounge_enabled | default(False))

    - role: tiddlywiki
      tags:
        - tiddlywiki
      when: (tiddlywiki_enabled | default(False))

    - role: timemachine
      tags:
        - timemachine
      when: (timemachine_enabled | default(False))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: transmission
      tags:
        - transmission
      when: (transmission_enabled | default(False))

    - role: transmission-with-openvpn
      tags:
        - transmission_with_openvpn
      when: (transmission_with_openvpn_enabled | default(False))

    - role: ubooquity
      tags:
        - ubooquity
      when: (ubooquity_enabled | default(False))

    - role: utorrent
      tags:
        - utorrent
      when: (utorrent_enabled | default(False))

    - role: virtual_desktop
      tags:
        - virtual_desktop
      when: (virtual_desktop_enabled | default(False))

    - role: wallabag
      tags:
        - wallabag
      when: (wallabag_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

    - role: wireshark
      tags:
        - wireshark
      when: (wireshark_enabled | default(False))

    - role: woodpecker-ci
      tags:
        - woodpecker_ci
      when: (woodpecker_ci_enabled | default(False))

    - role: youtubedlmaterial
      tags:
        - youtubedlmaterial
      when: (youtubedlmaterial_enabled | default(False))

    - role: znc
      tags:
        - znc
      when: (znc_enabled | default(False))

    - role: vscode-server
      tags:
        - vscode-server
      when: (vscode_server_enabled | default(False))

    - role: uptimekuma
      tags:
        - uptimekuma
      when: (uptimekuma_enabled | default(False))

    - role: samba
      tags:
        - samba
      when: (samba_enabled | default(False))

    - role: qbittorrent
      tags:
        - qbittorrent
      when: (qbittorrent_enabled | default(False))

    - role: photoprism
      tags:
        - photoprism
      when: (photoprism_enabled | default(False))

    - role: openbudgeteer
      tags:
        - openbudgeteer
      when: (openbudgeteer_enabled | default(False))
    - role: openbooks
      tags:
        - openbooks
      when: (openbooks_enabled | default(False))

    - role: prowlarr
      tags:
        - prowlarr
      when: (prowlarr_enabled | default(False))

    - role: linx
      tags:
        - linx
      when: (linx_enabled | default(False))

    - role: lidarr
      tags:
        - lidarr
      when: (lidarr_enabled | default(False))

    - role: jellyfin
      tags:
        - jellyfin
      when: (jellyfin_enabled | default(False))

    - role: guacamole
      tags:
        - guacamole
      when: (guacamole_enabled | default(False))

    - role: grafana
      tags:
        - grafana
      when: (grafana_enabled | default(False))

    - role: firefly-3
      tags:
        - firefly-3
      when: (firefly_3_enabled | default(False))

    - role: dozzle
      tags:
        - dozzle
      when: (dozzle_enabled | default(False))

    - role: cf-companion
      tags:
        - cf-companion
      when: (cf_companion_enabled | default(False))

    - role: cloudflare-ddns
      tags:
        - cloudflare-ddns
      when: (cloudflare_ddns_enabled | default(False))

    - role: server
      tags:
        - server
      when: (server_enabled | default(False))

    - role: autoheal
      tags:
        - autoheal
      when: (autoheal_enabled | default(False))

    - role: caddy
      tags:
        - caddy
      when: (caddy_enabled | default(False))

    - role: wireguard-gui
      tags:
        - wireguard-gui
      when: (wireguard_gui_enabled | default(False))

    - role: paperless_ng
      tags:
        - paperless_ng
      when: (paperless_ng_enabled | default(False))

    - role: homer
      tags:
        - homer
      when: (homer_enabled | default(False))

    - role: nginx_proxy_manager
      tags:
        - nginx_proxy_manager
      when: (nginx_proxy_manager_enabled | default(False))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: bazarr
      tags:
        - bazarr
      when: (bazarr_enabled | default(False))

    - role: emby
      tags:
        - emby
      when: (emby_enabled | default(False))

    - role: homeassistant
      tags:
        - homeassistant
      when: (homeassistant_enabled | default(False))

    - role: jackett
      tags:
        - jackett
      when: (jackett_enabled | default(False))

    - role: lidarr
      tags:
        - lidarr
      when: (lidarr_enabled | default(False))

    - role: minidlna
      tags:
        - minidlna
      when: (minidlna_enabled | default(False))

    - role: n8n
      tags:
        - n8n_enabled
      when: (n8n_enabled | default(False))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: prowlarr
      tags:
        - prowlarr
      when: (prowlarr_enabled | default(False))

    - role: ombi
      tags:
        - ombi
      when: (ombi_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(False))

    - role: syncthing_desktop
      tags:
        - syncthing_desktop
      when: (syncthing_desktop_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

    - role: webtop
      tags:
        - webtop
      when: (webtop_enabled | default(False))

    - role: pihole
      tags:
        - pihole
      when: (pihole_enabled | default(False))

    - role: vaultwarden
      tags:
        - vaultwarden
      when: (vaultwarden_enabled | default(False))

    - role: sabnzbd
      tags:
        - sabnzbd
      when: (sabnzbd_enabled | default(False))

    - role: beancount-fava
      tags:
        - beancount-fava
        - beancount
        - fava
      when: (beancount_fava_enabled | default(False))

    - role: duf
      tags:
        - duf
      when: (duf_enabled | default(False))

    - role: pigallery2
      tags:
        - pigallery2
      when: (pigallery2_enabled | default(False))

    - role: budge
      tags:
        - budge
      when: (budge_enabled | default(False))

    - role: audiobookshelf
      tags:
        - audiobookshelf
      when: (audiobookshelf_enabled | default(False))

    - role: deemix
      tags:
        - deemix
      when: (deemix_enabled | default(False))

    - role: dashdot
      tags:
        - dashdot
      when: (dashdot_enabled | default(False))

    - role: tmux
      tags:
        - tmux
      when: (tmux_enabled | default(False))

    - role: zsh
      tags:
        - zsh
      when: (zsh_enabled | default(False))

    - role: gantsign.oh-my-zsh
      tags:
        - oh-my-zsh
      when: (oh_my_zsh_enabled | default(False))

    - role: aur
      tags:
        - aur
      when: (aur_enabled | default(False))

    - role: archlinux
      tags:
        - archlinux
      when: (archlinux_enabled | default(False))

    - role: gnome
      tags:
        - gnome
      when: (gnome_enabled | default(False))

    - role: flatpak
      tags:
        - flatpak
      when: (flatpak_enabled | default(False))

    - role: snap
      tags:
        - snap
      when: (snap_enabled | default(False))

    - role: ssh
      tags:
        - ssh
      when: (ssh_enabled | default(False))
    - role: serviio
      tags:
        - serviio
      when: (serviio_enabled | default(False))
