---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 1.9.6
  - name: geerlingguy.docker
    version: 6.0.0
  - name: bertvv.samba
    version: v2.7.1
  - name: geerlingguy.nfs
    version: 2.0.0
  - name: geerlingguy.pip
  - name: geerlingguy.github-users
  - name: geerlingguy.dotfiles
  - name: geerlingguy.firewall
  - name: geerlingguy.security
  - name: geerlingguy.ntp
  - name: geerlingguy.go
  - name: geerlingguy.git
  - name: geerlingguy.ansible
  - name: geerlingguy.samba
  - name: petermosmans.customize-gnome
  - name: nginxinc.nginx
  - name: geerlingguy.docker_arm
    version: 5.0.0

  - name: hurricanehrndz.rustup
  - name: artis3n.tailscale
  - name: gantsign.oh-my-zsh
  - name: gantsign.pin-to-launcher

collections:
  - name: kewlfft.aur
  - name: ansible.posix
  - name: community.docker
  - name: community.general
