---
- name: Create bash shell aliases
  lineinfile: dest=/home/{{ user_name }}/.bashrc regexp='{{ item }}' insertafter='alias more=less' line='{{ item }}' owner='{{ user_name }}' state=present
  with_items: "{{ shell_aliases }}"
  become_user: '{{ user_name }}'
  become: yes
  tags:
    - bash
