---
- name: Update cache and upgrade
  community.general.pacman:
    update_cache: yes
    upgrade: yes
    upgrade_extra_args: "--noconfirm"
  become: true
  tags:
    - pre

- name: Install Utils
  community.general.pacman:
    name: '{{ utils }}'
    state: present
  become: true
  tags:
    - utils

- name: Install Utils from Arch User Repository
  ansible.builtin.shell: |
    set -o pipefail
    pamac build -d --no-confirm {{ item }} | grep "is up to date"
    if [ $? != 0 ]; then
      pamac build --no-confirm {{ item }}
    fi
  with_items: '{{ utils_aur }}'
  become: true
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  tags:
    - base
    - aur


- ansible.builtin.include_tasks:
    file: ntp.yml

- ansible.builtin.include_tasks:
    file: pip.yml

- ansible.builtin.include_tasks:
    file: bash.yml

- ansible.builtin.include_tasks:
    file: zsh.yml

- ansible.builtin.include_tasks:
    file: terminator.yml


- name: Creates Workspace directory
  ansible.builtin.file:
    path: /home/{{ user_name }}/Workspace
    state: directory
  become_user: '{{ user_name }}'
  become: true
