---
- name: Create webtop Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ webtop_data_directory }}"
  when: webtop_enabled is true


# - name: Template webtop config.toml
#   template:
#     src: webtop.toml
#     dest: "{{ webtop_data_directory }}/webtop.toml"
#   register: template_config

- name: webtop Docker Container
  docker_container:
    name: webtop
    image: "{{ webtop_docker_image }}"
    pull: true
    privileged : true
    volumes:
      - "{{ webtop_data_directory }}/config:/config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart_policy: unless-stopped
    ports:
      - 3000:3000
    env:
      TZ: "{{ ansible_nas_timezone }}"
      # PUID: "{{ webtop_user_id }}"
      # PGID: "{{ webtop_group_id }}"
      KEYBOARD: en-us-qwerty #optional
    # memory: "{{ webtop_memory }}"
    # recreate: "{{ template_config is changed }}"
    # labels:
    #   traefik.enable: "{{ webtop_available_externally }}"
    #   traefik.http.routers.webtop.rule: "Host(`{{ webtop_hostname }}.{{ ansible_nas_domain }}`)"
    #   traefik.http.routers.webtop.tls.certresolver: "letsencrypt"
    #   traefik.http.routers.webtop.tls.domains[0].main: "{{ ansible_nas_domain }}"
    #   traefik.http.routers.webtop.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
    #   traefik.http.services.webtop.loadbalancer.server.port: "3000"
  tags: webtop
  when: webtop_enabled is true

# # stop webtop
# - name: Stop webtop
#   docker_container:
#     name: webtop
#     state: stopped
#   when: webtop_enabled is not true

# # remove webtop
# - name: Remove webtop
#   docker_container:
#     name: webtop
#     state: absent
#   when: webtop_enabled is not true
