# if ubuntu install from apt
# if manjaro install from aur / flatpak
# if windows install from chocolatey


- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Windows.yml
  when: ansible_os_family == 'Windows'