---
- name: Create Semaphore Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ semaphore_data_directory }}"

- name: Semaphore Docker Container
  docker_container:
    name: "{{ semaphore_container_name }}"
    image: "{{ semaphore_docker_image }}"
    pull: true
    ports:
      - "{{semaphore_http_port}}:3000"
    volumes:
      - "{{ semaphore_data_directory }}/home:/etc/semaphore"
      - "{{ semaphore_data_directory }}/lib:/var/lib/semaphore" # database.boltdb location (Not required if using mysql or postgres)
    env:
      SEMAPHORE_DB_DIALECT: "{{ semaphore_db_dialect }}"
      SEMAPHORE_ADMIN_PASSWORD: "{{ semaphore_admin_password }}"
      SEMAPHORE_ADMIN_NAME: "{{ semaphore_admin_name }}"
      SEMAPHORE_ADMIN_EMAIL: "{{ semaphore_admin_email }}"
      SEMAPHORE_ADMIN: "{{ semaphore_admin }}"
    restart_policy: unless-stopped
