tw_gkeep_sync -t shopping_list -k "Shopping list"
tw_gkeep_sync -t home -k "Home"
tw_gkeep_sync -t test_tag -k "Test Note"
tw_gkeep_sync -t today -k "Today"
tw_gkeep_sync -t work -k "Work"
tw_gkeep_sync -t northernlion -k "Northernlion Streams"

# tw_gkeep_sync -t TODAY -k "Due: Today"
# tw_gkeep_sync -t TODAY work -k "Due: Today Work"
# tw_gkeep_sync -t TODAY home -k "Due: Today Home"