---
- name: Create homarr container
  community.docker.docker_container:
    name: "{{ homarr_container_name }}"
    image: "{{ homarr_docker_image }}"
    pull: true
    state: started
    volumes:
      - "{{ homarr_data_directory }}/icons:/app/public/icons"
      - "{{ homarr_data_directory }}/configs:/app/data/configs"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    ports:
      - "{{ homarr_port_http }}:7575"
    restart_policy: unless-stopped
