---
- import_tasks: syncthing_install.yml
  when: syncthing_pkg_enabled
- import_tasks: start.yml
  when: syncthing_package_enabled
- import_tasks: syncthing-docker.yml
  when: syncthing_docker_enabled


# this also includes ubuntu
- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: package

# - include: redhat.yml
#   when: ansible_os_family == 'RedHat'
#   tags: package

- include: arch.yml
  when: ansible_os_family == 'Archlinux'
  tags: package

- wait_for: port=8384 delay=3 timeout=5

# https://github.com/le9i0nx/ansible-syncthing/tree/master/tasks