---
- ansible.builtin.import_tasks:
    file: syncthing_install.yml
  when: syncthing_pkg_enabled

- ansible.builtin.import_tasks:
    file: start.yml
  when: syncthing_package_enabled

- ansible.builtin.import_tasks:
    file: syncthing-docker.yml
  when: syncthing_docker_enabled

- ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_os_family == 'Debian'
  tags: package

- ansible.builtin.include_tasks:
    file: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: package

- ansible.builtin.include_tasks:
    file: arch.yml
  when: ansible_os_family == 'Archlinux'
  tags: package

- ansible.builtin.wait_for:
    port: 8384
    delay: 3
    timeout: 5
# https://github.com/le9i0nx/ansible-syncthing/tree/master/tasks
