---

- name: Create uptime_kuma Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ uptime_kuma_data_directory }}"


- name: Uptime_kuma Docker Container
  community.docker.docker_container:
    name: uptime_kuma
    image: "louislam/uptime-kuma:1"
    pull: true
    ports:
    - "{{uptime_kuma_port}}:3001/tcp"
    volumes:
      - "{{ uptime_kuma_data_directory }}/app/data:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped
    memory: "{{ uptime_kuma_memory }}"
