---
- name: wireguard_gui Docker Container
  docker_container:
    name: wireguard_gui
    image: place1/wg-access-server
    pull: true
    volumes:
      # - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ wireguard_gui_data }}:/data"
    ports:
      - "{{ wireguard_tcp_port }}:8000/tcp"
      - "{{ wireguard_udp_port }}:51820/udp"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      WG_ADMIN_USERNAME: "{{wireguard_gui_admin_username}}"
      WG_ADMIN_PASSWORD: "{{wireguard_gui_admin_password}}"
      WG_WIREGUARD_PRIVATE_KEY: "{{ wireguard_gui_private_key }}"
      WG_EXTERNAL_HOST: "wireguard-vpn.{{ ansible_hostname }}"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped

