---
- name: Create pihole Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ pihole_data_directory }}"


- name: pihole Docker Container
  docker_container:
    name: pihole
    image: "{{ pihole_docker_image }}"
    pull: true
    # network_mode: host
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    capabilities:
      - NET_ADMIN
    volumes:
      - "{{ pihole_data_directory }}/etc/pihole:/etc/pihole/"
      - "{{ pihole_data_directory }}/etc/dnsmasq.d:/etc/dnsmasq.d/"
    env: "{{ pihole_environment_variables }}"
    restart_policy: unless-stopped
    memory: "{{ pihole_memory }}"
